//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudoDesktopApp.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JudoBaseEntities : DbContext
    {
        public JudoBaseEntities()
            : base("name=JudoBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeCategory> AgeCategories { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Hometown> Hometowns { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<SportsClub> SportsClubs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WeightCategory> WeightCategories { get; set; }
    }
}
